# Конфигурация песочницы для выполнения кода

# Общие настройки песочницы
sandbox:
  working_dir: "/home/smollm/workspace/code"
  temp_dir: "/home/smollm/workspace/temp"
  max_execution_time: 30  # Максимальное время выполнения в секундах
  max_output_size: 1048576  # Максимальный размер вывода (1MB)
  max_file_size: 10485760  # Максимальный размер файла (10MB)

# Ограничения ресурсов
limits:
  memory: 1024  # MB
  cpu: 50  # % от одного ядра
  disk: 8096  # MB
  processes: 20
  files: 1024

# Настройки языков программирования
languages:
  python:
    enabled: true
    command: "python3"
    file_extension: ".py"
    timeout: 30
    compile_check: ["-m", "py_compile"]
    run_args: []
    allowed_modules:
      - "math"
      - "random"
      - "datetime"
      - "json"
      - "re"
      - "collections"
      - "os.path"
      - "functools"
      - "itertools"
    blocked_modules:
      - "os"
      - "sys"
      - "subprocess"
      - "multiprocessing"
      - "socket"
      - "requests"

  javascript:
    enabled: true
    command: "node"
    file_extension: ".js"
    timeout: 30
    compile_check: ["--check"]
    run_args: []
    allowed_modules:
      - "fs"
      - "path"
      - "util"
      - "crypto"
      - "assert"
      - "buffer"
      - "events"
    blocked_modules:
      - "child_process"
      - "cluster"
      - "dgram"
      - "dns"
      - "http"
      - "https"
      - "net"

  go:
    enabled: true
    command: "go"
    file_extension: ".go"
    timeout: 60
    compile_check: ["build", "-o", "/dev/null"]
    run_args: ["run"]
    allowed_packages:
      - "fmt"
      - "strings"
      - "strconv"
      - "math"
      - "time"
      - "encoding/json"
      - "errors"
      - "sort"
    blocked_packages:
      - "os/exec"
      - "net"
      - "net/http"
      - "syscall"

  c:
    enabled: true
    command: "gcc"
    file_extension: ".c"
    timeout: 60
    compile_check: ["-fsyntax-only"]
    compile_args: ["-Wall", "-O2"]
    run_args: []